spring:
    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/cadastro-clientes
        username: postgres
        password: postgres
        driverClassName: org.postgresql.Driver
    security:
        token:
            secret: segredo
            expiration_time: 120